* Board Platformer
A Board Game AI Developing Platform

** Introduction
  Board Platformer is a generic board game AI developing platform.
  It supports manually playing agains provided AI process.
  And also automatic play for gathering stacks of game data.
  
** Current State
  Board Platformer is currently under very early development.
  The project is not even close to partially done, Everything is subject to change.
  Contributers are very welcome, However ask me first before jumping in.

  My personal development environment is Linux.
  Thus no support for different platforms are available.
  If your willing to contribute from a different platform,
  you'll first have to successfully create a build system of your own.
  (this alone will be a create contribution!)
  
** Development TODO list
   - [X] Logging system
   - [ ] Game server
   - [ ] GUI
   - [ ] Automatic Play 
   - [ ] Example Implementation
      
** Dependencies
   - [[https://grpc.io][grpc]]
   - [[https://developers.google.com/protocol-buffers/][protobuf]]
   - [[http://nanapro.org/en-us/][nana]]
   - [[http://www.boost.org/][boost]]
     + [[http://www.boost.org/doc/libs/1_64_0/libs/filesystem/doc/index.htm][filesystem]]
     + [[http://www.boost.org/doc/libs/1_64_0/libs/filesystem/doc/index.htm][system]]
     + [[http://www.boost.org/doc/libs/1_64_0/doc/html/process.html][process]]
   - threads
   - standard filesystem
     
** License

   Board Platformer. A Board Game AI Developing Platform                     
   Copyright (C) 2017  Red-Portal                                            
                                                                           
   This program is free software: you can redistribute it and/or modify  
   it under the terms of the GNU General Public License as published by  
   the Free Software Foundation, either version 3 of the License, or     
   (at your option) any later version.                                   
   
   This program is distributed in the hope that it will be useful,       
   but WITHOUT ANY WARRANTY; without even the implied warranty of        
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         
   GNU General Public License for more details.                        
   
   You should have received a copy of the GNU General Public License     
   along with this program.  If not, see <http://www.gnu.org/licenses/>. 
   
