// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rpc_message.proto
#ifndef GRPC_rpc_5fmessage_2eproto__INCLUDED
#define GRPC_rpc_5fmessage_2eproto__INCLUDED

#include "rpc_message.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

class board_platformer_comm final {
 public:
  static constexpr char const* service_full_name() {
    return "board_platformer_comm";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status send_board_state(::grpc::ClientContext* context, const ::board_state& request, ::player_move* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::player_move>> Asyncsend_board_state(::grpc::ClientContext* context, const ::board_state& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::player_move>>(Asyncsend_board_stateRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::player_move>* Asyncsend_board_stateRaw(::grpc::ClientContext* context, const ::board_state& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status send_board_state(::grpc::ClientContext* context, const ::board_state& request, ::player_move* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::player_move>> Asyncsend_board_state(::grpc::ClientContext* context, const ::board_state& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::player_move>>(Asyncsend_board_stateRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::player_move>* Asyncsend_board_stateRaw(::grpc::ClientContext* context, const ::board_state& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::RpcMethod rpcmethod_send_board_state_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status send_board_state(::grpc::ServerContext* context, const ::board_state* request, ::player_move* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_send_board_state : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_send_board_state() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_send_board_state() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_board_state(::grpc::ServerContext* context, const ::board_state* request, ::player_move* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsend_board_state(::grpc::ServerContext* context, ::board_state* request, ::grpc::ServerAsyncResponseWriter< ::player_move>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_send_board_state<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_send_board_state : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_send_board_state() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_send_board_state() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status send_board_state(::grpc::ServerContext* context, const ::board_state* request, ::player_move* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_send_board_state : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_send_board_state() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::StreamedUnaryHandler< ::board_state, ::player_move>(std::bind(&WithStreamedUnaryMethod_send_board_state<BaseClass>::Streamedsend_board_state, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_send_board_state() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status send_board_state(::grpc::ServerContext* context, const ::board_state* request, ::player_move* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedsend_board_state(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::board_state,::player_move>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_send_board_state<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_send_board_state<Service > StreamedService;
};


#endif  // GRPC_rpc_5fmessage_2eproto__INCLUDED
